🔧 Add code coverage report generation
This adds support for code-coverage report generation, as well as
minimum-required coverage. If a change does not satisfy the minimum
code-coverage lines coverage total, the check fails.

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -126,3 +126,52 @@ jobs:
 
       - name: Test
         run: cargo test --verbose
+
+  coverage:
+    name: Code Coverage
+    runs-on: ${{ matrix.os }}
+    needs: [build, test]
+    strategy:
+      matrix:
+        os:
+          - ubuntu-latest
+          - macos-latest
+          - windows-latest
+    defaults:
+      run:
+        shell: bash
+    env:
+      OUTPUT_FILE: ${{matrix.os}}-codecov.json
+      COVERAGE_MINIMUM: ${{ 70.0 }}
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Install toolchain
+        uses: ./.github/actions/rust-toolchain
+
+      - name: Install cargo-llvm-cov
+        uses: taiki-e/install-action@cargo-llvm-cov
+
+      - name: Generate Coverage Report
+        id: report
+        run: |
+          cargo llvm-cov --json --output-path ${{ env.OUTPUT_FILE }}
+          echo "coverage=$(cat ${{ env.OUTPUT_FILE }})" >> "${GITHUB_OUTPUT}"
+
+      - name: Check Coverage Requirement
+        env:
+          COVERAGE: ${{fromJson(steps.report.outputs.coverage).data[0].totals.lines.percent}}
+        run: |
+          if [[ ${{env.COVERAGE_MINIMUM}} > ${{env.COVERAGE}} ]]; then
+            echo "Error: Code coverage '${COVERAGE}%' is below this project's minimum '${COVERAGE_MINIMUM}%'!" >&2
+            exit 1
+          fi
+
+      - name: Upload Artifact
+        uses: actions/upload-artifact@v1
+        if: success() || failure()
+        with:
+          name: ${{env.OUTPUT_FILE}}
+          path: ${{env.OUTPUT_FILE}}
